const NEXT_PUBLIC_TELEMORA_ADDRESS = process.env.NEXT_PUBLIC_TELEMORA_ADDRESS;
const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL;
const NEXT_PUBLIC_SMART_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_SMART_CONTRACT_ADDRESS;
const NEXT_PUBLIC_COMMISSION_PERCENTAGE = process.env.NEXT_PUBLIC_COMMISSION_PERCENTAGE ?? '2.5';

if (!NEXT_PUBLIC_API_URL) throw new Error('Missing NEXT_PUBLIC_API_URL env');

if (!NEXT_PUBLIC_TELEMORA_ADDRESS) throw new Error('Missing NEXT_PUBLIC_TELEMORA_ADDRESS env');

if (!NEXT_PUBLIC_SMART_CONTRACT_ADDRESS)
  throw new Error('Missing NEXT_PUBLIC_SMART_CONTRACT_ADDRESS env');

export const environment = {
  apiUrl: NEXT_PUBLIC_API_URL,
  marketplaceAddress: NEXT_PUBLIC_TELEMORA_ADDRESS,
  smartContractAddress: NEXT_PUBLIC_SMART_CONTRACT_ADDRESS,
  commissionPercent: parseFloat(NEXT_PUBLIC_COMMISSION_PERCENTAGE),
};
